spring:
  datasource:
    driver-Class-Name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pos_tree
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "397003871219-iu2vl90k0vogk4qb0li6kdohmuetc105.apps.googleusercontent.com"
            client-secret:
            scope: "profile, email"
            redirect-uri: "http://localhost:8080"
          naver:
            client-id: "kEz83Zwu754Dn_PQ0ZK2"
            client-secret:
            scope: "name, email"
            client-name: "Naver"
            authorization-grant-type: "authorization_code"
            redirect-uri: "http://localhost:8080/oauth/naver/callback"
        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openai.naver.com/v1/nid/me"
            user-name-attribute: "response"
